### ISSUE TITLE
problem in the operation of GPS positioning on smartphone.

### ISSUE THREAD

**Issue by u4y0u** [flacombe/gespot#4]
Hello, there is a problem in the operation of GPS positioning on smartphone.
As soon as you press the icon, a **red line** appears which remains as long as you have not closed the page. It is therefore impossible to trace a displacement afterwards or to reactivate / deactivate this function.
----
Bonjour, il y a un problème dans le fonctionnement du positionnement par GPS sur smartphone.
Dès que l'on appuie sur l'icône, il apparait un **trait rouge** qui reste tant que l'on à pas fermé la page. Il est donc impossible de tracer un déplacement ensuite ou de réactiver/désactiver cette fonction.

Screenshot at launch and after pressing the icon. / Copie d'écran au lancement et après avoir appuyé sur l'icône.

![Screenshot_20200914-182452](https://user-images.githubusercontent.com/54479065/93112294-1da52900-f6b8-11ea-9acd-aaa5fb5f40b9.jpg)
![Screenshot_20200914-172825](https://user-images.githubusercontent.com/54479065/93112303-21d14680-f6b8-11ea-9f47-1b6675fb223c.jpg)

**Comment by flacombe** [comment]
Ce problème vient du fait que HTTPS n'était pas activé sur le service. Mapbox n'autorise le partage de l'information de position uniquement avec https.

C'est désormais chose faite et la localisation fonctionne bien !
Merci d'avoir signalé le problème
